### PR TITLE
Update Cantarell to version 0.0.18.1

### PR DESCRIPTION
**Pull request by fitojb**
The update features:
- Improved Latin shapes
- Assorted fixes to diacritics and punctuation
- Cyrillic coverage
- Numerous improvements to metrics and spacing
- Better rendering
- Many new symbols

### CODE REVIEW

**Comment by jancborchardt** [comment]
@davelab6 @jimmac I guess you probably know if this is correct and can review this? :)

**Comment by davelab6** [comment]
We can't just remove the italic files; nor can we update the romans to add more glyphs without also updating the italics to match. 

Since Cantarell is genuinely popular, I'm hoping to arrange for expanding it to resolve these blocking issues. In the mean time, https://www.google.com/fonts/specimen/Cambay is available with much of the updated design.

**Comment by davelab6** [comment]
Oh! This is for the opensourcedesign org, not the google org :) The 'fonts' repo name had me fooled for a moment. Sure, updating this here is good :)

**Comment by jancborchardt** [comment]
Should we rather replace Cantarell with Cambay then? Also cc @anexasajoop

**Comment by jimmac** [comment]
If the lack of oblique is the only obstruction standing in the way of updating Cantarell on google fonts, I'll see about generating it using FF.

**Comment by davelab6** [comment]
It also needs glyph parity :(

**Comment by anexasajoop** [comment]
I'm busy till the middle of next month, but after than I can look over what needs to be done for glyph parity, in terms adding glyphs from one version to another, or resizing them, if that helps.

**Comment by davelab6** [comment]
Thanks Pooja!

Sadly I don't believe the v1.0 approach of obliquing the Roman and tweaking
a few glyphs will suffice for Cyrillic.

**Comment by anexasajoop** [comment]
A proper italic for Cantarell would be so great!

**Comment by fitojb** [comment]
Since no one cares to follow up and merge…

**Comment by simonv3** [comment]
@fitojb looking at the above conversation I don't think no one cared to follow up, maybe life just happened. I wasn't paying attention to this PR so I'm not sure what was originally proposed, but it did look like there was some interest!

**Comment by davelab6** [comment]
I agree. Pooja are you interested to do this detailing work?

**Pull request closed without merging**
