### PR TITLE
Updated OCRA and OCRB fonts

### PR DESCRIPTION
**Pull request by GitBruno**
Font `OCRBS.otf` was missing from this repo whilst available from original source.

I have updated the OCRA to the same source. So both OCRA and OCRB come from same source (Derived from https://ctan.org/tex-archive/fonts/ocr-a as stated in the ocr.pdf)

It might be good to put both fonts in the same folder called `OCR` so we don't need a duplicate copy of `ocr.pdf` ?

### CODE REVIEW

**Comment by jancborchardt** [comment]
> It might be good to put both fonts in the same folder called OCR so we don't need a duplicate copy of ocr.pdf ?

@GitBruno good idea, want to update your pull request to do that? :)

**Comment by GitBruno** [comment]
Done

**Review by m1guelpf — APPROVED** [review]

**Comment by jancborchardt** [comment]
Looks good, thanks! :)

**Comment by jancborchardt** [comment]
Ah just one thing - I'd remove the subfolders OCRA and OCRB to keep it simple. I also thought that's what you meant. :)

**Comment by GitBruno** [comment]
You are right about that!

**Pull request merged**
