### PR TITLE
Added some fonts to the repo for easy cloning.

### PR DESCRIPTION
**Pull request by qwazix**
Collecting a bunch of FLOSS fonts is a pain, because of different download locations, archive types, ad-supported sites with waiting times etc.

I think it's a very nice service to have them all ready to clone into the OS fonts folder, as lists exist elsewhere too.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! We need the license files for the other typefaces as well though. Can you add that?

**Comment by qwazix** [comment]
Yes, but that might take some time. I'll try to do it as soon as possible.

**Comment by qwazix** [comment]
I have added all the license files. I think we can merge now.

**Comment by jancborchardt** [comment]
Great stuff, thank you @qwazix! :)

**Pull request merged**
